### ISSUE TITLE
貌似是版本问题，运行不了呀一直报错

### ISSUE THREAD

**Issue by JoeyFrancisTribbiani** [zlyyyy/bilibili-vue#1]
项目down下来以后运行
npm i
npm i --only=dev
npm run dev
然后
![image](https://user-images.githubusercontent.com/26857248/60005827-db05c400-96a1-11e9-9e3f-99c311bb3863.png)
这几天折腾了好久，最后还是没能成功运行。前端新手，大佬帮忙看看

**Comment by JoeyFrancisTribbiani** [comment]
？？？大佬？

**Comment by zlyyyy** [comment]
谢谢你的关注，抱歉这么晚看到你的问题，最近太忙了，这个应该是webpack与webpack-cli版本不兼容的问题，我本地试着处理了下。试了几种方式都没解决，索性直接升级了，你重新拉取一下master的代码，看一下我更新的readme，现在本地跑起来应该没什么问题了，后续我会优化一下代码

**Comment by JoeyFrancisTribbiani** [comment]
> 谢谢你的关注，抱歉这么晚看到你的问题，最近太忙了，这个应该是webpack与webpack-cli版本不兼容的问题，我本地试着处理了下。试了几种方式都没解决，索性直接升级了，你重新拉取一下master的代码，看一下我更新的readme，现在本地跑起来应该没什么问题了，后续我会优化一下代码

哈哈收到，我已经用新版本的vue-cli跑起来了，搭了个项目，把你代码拷贝进去没有问题，这个过程中学到了很多，感谢回复，以后继续探讨

**Comment by zlyyyy** [comment]
不客气，其实最重要的就是那个src，其他的都可以随意改变
