### ISSUE TITLE
files may have any casing exception

### ISSUE THREAD

**Issue by serfend** [zlyyyy/bilibili-vue#5]
WARNING  Compiled with 1 warnings                                                                                                           22:15:14
 warning  in (webpack)/buildin/global.js

There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Users\huawei\Documents\GitHub\bilibili-vue\node_modules\webpack\buildin\global.js
    Used by 2 module(s), i. e.
    C:\Users\huawei\Documents\GitHub\bilibili-vue\node_modules\sockjs-client\dist\sockjs.js
* C:\Users\huawei\Documents\github\bilibili-vue\node_modules\webpack\buildin\global.js
    Used by 3 module(s), i. e.
    C:\Users\huawei\Documents\github\bilibili-vue\node_modules\vue\dist\vue.runtime.esm.js

**Comment by zlyyyy** [comment]
我试了下本地没看到报这个错

**Comment by serfend** [comment]
似乎是`Documents\Github` with `Documents\github`导致的，但还不清楚为什么同一个项目里出现不同的路径

**Comment by zlyyyy** [comment]
看着是node_modules的问题，试试删除node_modules 重装下依赖看看还有没有这个问题

**Comment by serfend** [comment]
已经尝试但不限于删除node_modules、使用代理/淘宝镜像在yarn、npm安装、修改终端路径大小写等措施，暂时没有效果

**Comment by zlyyyy** [comment]
试一下，将项目放到一个路径没有大写字母的文件夹下
